
service: projectbase

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'local'}
  region: ${opt:region, 'us-east-1'}
  profile: projectbase-${self:custom.env-key}
  stackName: ${file(./serverless.config.js):stackName}
  apiGateway: 
    shouldStartNameWithService: true
    description: ${self:provider.stackName} API 
    binaryMediaTypes:
      - '*/*'
  deploymentBucket: 
    name: ${self:provider.stackName}-sls-state
    serverSideEncryption: AES256
  environment:
    # API_ENDPOINT: { "Fn::Join" : ["", ["https://", { "Ref" : "ApiGatewayRestApi" }, ".execute-api.${self:custom.region}.amazonaws.com" ] ] }
    STAGE: '${self:provider.stage}'
    AWS_PROFILE: '${self:provider.profile}'
    API_SEGMENT: '${self:custom.apiSegment}'

plugins:
  - serverless-offline
  - serverless-webpack
  - '@animus-bi/fs-sls'
  - serverless-deployment-bucket

custom:
  region: ${self:provider.region}
  env-key:  ${file(./serverless.config.js):env.key}
  isEphemeral: ${file(./serverless.config.js):env.isEphemeral}
  webAccessLogName: ${self:provider.stackName}-web-accesslogs
  domainName: animus-bi.com
  apiSegment: api
  certificateArn: arn:aws:acm:us-east-1:223673446499:certificate/81d4e238-6bb9-4ac5-8409-3dcc6dd97ed7
  fqdn: ${file(./serverless.config.js):fqdn}
  deploymentBucket:
    versioning: true
    accelerate: true
    blockPublicAccess: true
    tags:
      - Key: Environment
        Value: ${self:provider.stage}
  webpack:
    includeModules: true
    forceExclude:
      - aws-sdk
  fs-sls:
    ${file(./infra/web/fs-sls.yml)}

functions:
  - ${file(./infra/api/handler-events.yml)}

resources: 
  - ${file(./infra/web/web-access-log-bucket.resources.yml)}
  - ${file(./infra/web/web-cf-cname.resouces.yml)}
  - ${file(./infra/api/apigw-cf-name.resources.yml)}
  