name: 'Deploy to environments on the path to production'
description: 'Orchestrates path-to-prod deployments'
inputs:
  command:
    required: yes
  config:
    required: yes
  credentials:
    required: yes
  reversionToken:
    required: yes
  qualifyReversion:
    required: yes
  integrationBranch:
    required: no
    default: master
runs:
  using: "composite"
  steps:
    - uses: ./.github/workflows/composite/tag-validator
      id: tagValidator
      with:
        version: "${{ github.ref_name }}"
        reversionToken: ${{ inputs.reversionToken }}
        qualifyReversion: ${{ inputs.qualifyReversion }}
    - uses: ./.github/workflows/composite/checkout-tag-and-match-product-versions
      with: 
        validationResult: "${{ steps.tagValidator.outputs.result }}"
        integrationBranch: ${{ inputs.integrationBranch }}
    - uses: ./.github/workflows/composite/job-defaults
    - uses: ./.github/workflows/composite/deploy-setup
      with:
        config: ${{ inputs.config }}
        credentials: ${{ inputs.credentials }}
    - run: "${{ inputs.command }}"
      shell: bash
    - uses: ./.github/workflows/composite/deploy-teardown