Resources:
  WebBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:service}-web-${self:provider.stage}
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
    DeletionPolicy: Delete
Outputs:
  WebBucketNameOutputKey:
    Value: !Ref WebBucket