appMessage:
  handler: src/handlers/api/app.message
  events:
  - http:
      path: api/app
      private: false
      method: get
      request:
        parameters:
          querystrings:
            message: true