Resources:
  UserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      ClientName: ${self:custom.userPoolClientName}
      GenerateSecret: False
      UserPoolId:
        Ref: UserPool