name: Ephemeral Environment Cleanup

on: delete

jobs:
  undeploy-branch-env: 
    name: "Undeploy Branch"
    runs-on: ubuntu-latest
    if: ${{ github.event.ref_type == 'branch' && github.ref != 'refs/heads/master' }}
    environment:
      name: nonprod
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/job-defaults
      - uses: ./.github/workflows/composite/deploy-setup
        with:
          config: ${{ secrets.AWS_CONFIG }}
          credentials: ${{ secrets.AWS_CREDENTIALS }}
      - run: mkdir -p src/web/build
      - run: npm run undeploy:nonprod
      - uses: ./.github/workflows/composite/deploy-teardown
