name: Ephemeral Environment Deployment

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  quality-gate:
    uses: ./.github/workflows/quality-gates.yml

  deploy-ephemeral-env:
    name: Deploy to ephemeral
    runs-on: ubuntu-latest
    needs: [quality-gate]
    environment:
      name: nonprod
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/deploy-dev-or-ephemeral
        with:
          command: npm run deploy:nonprod
          config: ${{ secrets.AWS_CONFIG }}
          credentials: ${{ secrets.AWS_CREDENTIALS }}
