name: Branch Deployment

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  quality-gate:
    uses: ./.github/workflows/quality-gates-workflow.yml

  deploy-data-migrations:
    name: Data Migrations
    runs-on: ubuntu-latest
    needs: [ quality-gate ]
    environment: 
      name: nonprod
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/data-migrations
        with:
          stage: nonprod
          config: ${{ secrets.AWS_CONFIG }}
          credentials: ${{ secrets.AWS_CREDENTIALS }}

  deploy-infrastructure-and-app:
    name: App & Infra
    runs-on: ubuntu-latest
    needs: [deploy-data-migrations]
    environment:
      name: nonprod
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/aws-connected-command
        with:
          command: npm run deploy:nonprod
          config: ${{ secrets.AWS_CONFIG }}
          credentials: ${{ secrets.AWS_CREDENTIALS }}
