name: Branch Deployment

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  quality-gate:
    uses: ./.github/workflows/quality-gates.yml

  deploy-branch-env:
    name: Deploy Branch
    runs-on: ubuntu-latest
    needs: [quality-gate]
    environment:
      name: nonprod
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/deploy-dev-or-branch
        with:
          command: npm run deploy:nonprod
          config: ${{ secrets.AWS_CONFIG }}
          credentials: ${{ secrets.AWS_CREDENTIALS }}
