name: CI/CD Quality Gates

on:
  workflow_call:

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/job-defaults
      - run: npm run lint:ci

  unit-test-client:
    name: Client Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/job-defaults
      - run:  |
          cd src/web
          npm run test-unit:ci
          cd -
      - name: Upload client coverage to github
        if: always()
        uses: actions/upload-artifact@v2
        with: 
          name: client-unit-test-artifacts
          path: src/web/coverage

  unit-test-api:
    name: API Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/job-defaults
      - run: npm run test-unit:ci
      - name: Upload api coverage to github
        if: always()
        uses: actions/upload-artifact@v2
        with: 
          name: api-unit-test-artifacts
          path: coverage
  
  integration-test-client:
    name: Client Integration Tests
    runs-on: ubuntu-latest
    needs: [unit-test-client, unit-test-api]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/job-defaults
      - run:  |
          cd src/web
          npm run test-integration:ci
          cd -
        shell: bash
      - name: Upload client integration artifacts to github
        if: always()
        uses: actions/upload-artifact@v2
        with: 
          name: client-integration-test-artifacts
          path: |
            src/web/cypress/screenshots
            src/web/cypress/videos

  integration-test-api:
    name: API Integration Tests
    runs-on: ubuntu-latest
    needs: [unit-test-client, unit-test-api]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/job-defaults
      - run: npm run test-integration:ci
        shell: bash
      - name: Upload client integration artifacts to github
        if: always()
        uses: actions/upload-artifact@v2
        with: 
          name: api-integration-test-artifacts
          path: |
            cypress/screenshots
            cypress/videos

